// @generated by xap-specs codegen (xap-specs/src/bin/codegen.rs). Do not edit.
// include!d into xap-wasm/src/lib.rs; relies on that module's scope for
// `XapWasmClient`, `query`, `to_js`, `jserr_str`, `Uuid`, and the
// wasm_bindgen prelude. Type paths are fully qualified to avoid import coupling.
#[wasm_bindgen]
impl XapWasmClient {
    pub fn xap_version(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(inner, id, xap_specs::spec::xap::XapVersionRequest(())).await?;
            to_js(&resp)
        })
    }

    pub fn xap_capabilities(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(inner, id, xap_specs::spec::xap::XapCapabilitiesRequest(())).await?;
            to_js(&resp)
        })
    }

    pub fn xap_enabled_subsystem_capabilities(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::xap::XapEnabledSubsystemCapabilitiesRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn xap_secure_status(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(inner, id, xap_specs::spec::xap::XapSecureStatusRequest(())).await?;
            to_js(&resp)
        })
    }

    pub fn xap_secure_unlock(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(inner, id, xap_specs::spec::xap::XapSecureUnlockRequest(())).await?;
            to_js(&resp)
        })
    }

    pub fn xap_secure_lock(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(inner, id, xap_specs::spec::xap::XapSecureLockRequest(())).await?;
            to_js(&resp)
        })
    }

    pub fn qmk_version(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(inner, id, xap_specs::spec::qmk::QmkVersionRequest(())).await?;
            to_js(&resp)
        })
    }

    pub fn qmk_capabilities(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(inner, id, xap_specs::spec::qmk::QmkCapabilitiesRequest(())).await?;
            to_js(&resp)
        })
    }

    pub fn qmk_board_identifiers(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::qmk::QmkBoardIdentifiersRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn qmk_board_manufacturer(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::qmk::QmkBoardManufacturerRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn qmk_product_name(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(inner, id, xap_specs::spec::qmk::QmkProductNameRequest(())).await?;
            to_js(&resp)
        })
    }

    pub fn qmk_config_blob_length(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::qmk::QmkConfigBlobLengthRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn qmk_config_blob_chunk(&self, device_id: String, arg: JsValue) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let arg: u16 = serde_wasm_bindgen::from_value(arg).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::qmk::QmkConfigBlobChunkRequest(arg),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn qmk_jump_to_bootloader(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::qmk::QmkJumpToBootloaderRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn qmk_hardware_identifier(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::qmk::QmkHardwareIdentifierRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn qmk_reinitialize_eeprom(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::qmk::QmkReinitializeEepromRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn keymap_capabilities(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::keymap::KeymapCapabilitiesRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn keymap_get_layer_count(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::keymap::KeymapGetLayerCountRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn keymap_get_keycode(&self, device_id: String, arg: JsValue) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let arg: xap_specs::spec::keymap::KeymapGetKeycodeArg =
                serde_wasm_bindgen::from_value(arg).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::keymap::KeymapGetKeycodeRequest(arg),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn keymap_get_encoder_keycode(&self, device_id: String, arg: JsValue) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let arg: xap_specs::spec::keymap::KeymapGetEncoderKeycodeArg =
                serde_wasm_bindgen::from_value(arg).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::keymap::KeymapGetEncoderKeycodeRequest(arg),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn remapping_capabilities(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::remapping::RemappingCapabilitiesRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn remapping_get_layer_count(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::remapping::RemappingGetLayerCountRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn remapping_set_keycode(&self, device_id: String, arg: JsValue) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let arg: xap_specs::spec::remapping::RemappingSetKeycodeArg =
                serde_wasm_bindgen::from_value(arg).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::remapping::RemappingSetKeycodeRequest(arg),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn remapping_set_encoder_keycode(
        &self,
        device_id: String,
        arg: JsValue,
    ) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let arg: xap_specs::spec::remapping::RemappingSetEncoderKeycodeArg =
                serde_wasm_bindgen::from_value(arg).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::remapping::RemappingSetEncoderKeycodeRequest(arg),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn lighting_capabilities(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::lighting::LightingCapabilitiesRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn backlight_capabilities(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::lighting::backlight::BacklightCapabilitiesRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn backlight_get_enabled_effects(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::lighting::backlight::BacklightGetEnabledEffectsRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn backlight_get_config(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::lighting::backlight::BacklightGetConfigRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn backlight_set_config(&self, device_id: String, arg: JsValue) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let arg: xap_specs::spec::types::BacklightConfig =
                serde_wasm_bindgen::from_value(arg).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::lighting::backlight::BacklightSetConfigRequest(arg),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn backlight_save_config(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::lighting::backlight::BacklightSaveConfigRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn rgblight_capabilities(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::lighting::rgblight::RgblightCapabilitiesRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn rgblight_get_enabled_effects(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::lighting::rgblight::RgblightGetEnabledEffectsRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn rgblight_get_config(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::lighting::rgblight::RgblightGetConfigRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn rgblight_set_config(&self, device_id: String, arg: JsValue) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let arg: xap_specs::spec::types::RgbLightConfig =
                serde_wasm_bindgen::from_value(arg).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::lighting::rgblight::RgblightSetConfigRequest(arg),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn rgblight_save_config(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::lighting::rgblight::RgblightSaveConfigRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn rgbmatrix_capabilities(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::lighting::rgbmatrix::RgbmatrixCapabilitiesRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn rgbmatrix_get_enabled_effects(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::lighting::rgbmatrix::RgbmatrixGetEnabledEffectsRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn rgbmatrix_get_config(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::lighting::rgbmatrix::RgbmatrixGetConfigRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn rgbmatrix_set_config(&self, device_id: String, arg: JsValue) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let arg: xap_specs::spec::types::RgbMatrixConfig =
                serde_wasm_bindgen::from_value(arg).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::lighting::rgbmatrix::RgbmatrixSetConfigRequest(arg),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn rgbmatrix_save_config(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::lighting::rgbmatrix::RgbmatrixSaveConfigRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn audio_capabilities(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::audio::AudioCapabilitiesRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn audio_get_config(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(inner, id, xap_specs::spec::audio::AudioGetConfigRequest(())).await?;
            to_js(&resp)
        })
    }

    pub fn audio_set_config(&self, device_id: String, arg: JsValue) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let arg: xap_specs::spec::types::AudioConfig =
                serde_wasm_bindgen::from_value(arg).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::audio::AudioSetConfigRequest(arg),
            )
            .await?;
            to_js(&resp)
        })
    }

    pub fn audio_save_config(&self, device_id: String) -> js_sys::Promise {
        let inner = self.inner.clone();
        wasm_bindgen_futures::future_to_promise(async move {
            let id = Uuid::parse_str(&device_id).map_err(jserr_str)?;
            let resp = query(
                inner,
                id,
                xap_specs::spec::audio::AudioSaveConfigRequest(()),
            )
            .await?;
            to_js(&resp)
        })
    }
}
