[package]
name = "xap-core"
version = "0.1.0"
edition = "2021"

[dependencies]
xap-specs = { path = "../xap-specs" }
binrw = "0.13"
flate2 = "1.0"
uuid = { version = "1.8", features = ["serde", "v4"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
specta = { version = "=2.0.0-rc.12", features = ["uuid"] }
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
async-trait = "0.1"

[dev-dependencies]
pollster = "0.4"
