// @generated by xap-specs codegen (xap-specs/src/bin/codegen.rs). Do not edit.
import type { XapWasmClient } from '@generated/xap-wasm/xap_wasm.js'

type Wrap = <T>(
    p: Promise<T>,
) => Promise<{ status: 'ok'; data: T } | { status: 'error'; error: string }>

export const generatedCommands = (ensureClient: () => Promise<XapWasmClient>, wrap: Wrap) => ({
    xapVersion: (id: string) => wrap(ensureClient().then((c) => c.xap_version(id))),
    xapCapabilities: (id: string) => wrap(ensureClient().then((c) => c.xap_capabilities(id))),
    xapEnabledSubsystemCapabilities: (id: string) =>
        wrap(ensureClient().then((c) => c.xap_enabled_subsystem_capabilities(id))),
    xapSecureStatus: (id: string) => wrap(ensureClient().then((c) => c.xap_secure_status(id))),
    xapSecureUnlock: (id: string) => wrap(ensureClient().then((c) => c.xap_secure_unlock(id))),
    xapSecureLock: (id: string) => wrap(ensureClient().then((c) => c.xap_secure_lock(id))),
    qmkVersion: (id: string) => wrap(ensureClient().then((c) => c.qmk_version(id))),
    qmkCapabilities: (id: string) => wrap(ensureClient().then((c) => c.qmk_capabilities(id))),
    qmkBoardIdentifiers: (id: string) =>
        wrap(ensureClient().then((c) => c.qmk_board_identifiers(id))),
    qmkBoardManufacturer: (id: string) =>
        wrap(ensureClient().then((c) => c.qmk_board_manufacturer(id))),
    qmkProductName: (id: string) => wrap(ensureClient().then((c) => c.qmk_product_name(id))),
    qmkConfigBlobLength: (id: string) =>
        wrap(ensureClient().then((c) => c.qmk_config_blob_length(id))),
    qmkConfigBlobChunk: (id: string, arg: unknown) =>
        wrap(ensureClient().then((c) => c.qmk_config_blob_chunk(id, arg))),
    qmkJumpToBootloader: (id: string) =>
        wrap(ensureClient().then((c) => c.qmk_jump_to_bootloader(id))),
    qmkHardwareIdentifier: (id: string) =>
        wrap(ensureClient().then((c) => c.qmk_hardware_identifier(id))),
    qmkReinitializeEeprom: (id: string) =>
        wrap(ensureClient().then((c) => c.qmk_reinitialize_eeprom(id))),
    keymapCapabilities: (id: string) => wrap(ensureClient().then((c) => c.keymap_capabilities(id))),
    keymapGetLayerCount: (id: string) =>
        wrap(ensureClient().then((c) => c.keymap_get_layer_count(id))),
    keymapGetKeycode: (id: string, arg: unknown) =>
        wrap(ensureClient().then((c) => c.keymap_get_keycode(id, arg))),
    keymapGetEncoderKeycode: (id: string, arg: unknown) =>
        wrap(ensureClient().then((c) => c.keymap_get_encoder_keycode(id, arg))),
    remappingCapabilities: (id: string) =>
        wrap(ensureClient().then((c) => c.remapping_capabilities(id))),
    remappingGetLayerCount: (id: string) =>
        wrap(ensureClient().then((c) => c.remapping_get_layer_count(id))),
    remappingSetKeycode: (id: string, arg: unknown) =>
        wrap(ensureClient().then((c) => c.remapping_set_keycode(id, arg))),
    remappingSetEncoderKeycode: (id: string, arg: unknown) =>
        wrap(ensureClient().then((c) => c.remapping_set_encoder_keycode(id, arg))),
    lightingCapabilities: (id: string) =>
        wrap(ensureClient().then((c) => c.lighting_capabilities(id))),
    backlightCapabilities: (id: string) =>
        wrap(ensureClient().then((c) => c.backlight_capabilities(id))),
    backlightGetEnabledEffects: (id: string) =>
        wrap(ensureClient().then((c) => c.backlight_get_enabled_effects(id))),
    backlightGetConfig: (id: string) =>
        wrap(ensureClient().then((c) => c.backlight_get_config(id))),
    backlightSetConfig: (id: string, arg: unknown) =>
        wrap(ensureClient().then((c) => c.backlight_set_config(id, arg))),
    backlightSaveConfig: (id: string) =>
        wrap(ensureClient().then((c) => c.backlight_save_config(id))),
    rgblightCapabilities: (id: string) =>
        wrap(ensureClient().then((c) => c.rgblight_capabilities(id))),
    rgblightGetEnabledEffects: (id: string) =>
        wrap(ensureClient().then((c) => c.rgblight_get_enabled_effects(id))),
    rgblightGetConfig: (id: string) => wrap(ensureClient().then((c) => c.rgblight_get_config(id))),
    rgblightSetConfig: (id: string, arg: unknown) =>
        wrap(ensureClient().then((c) => c.rgblight_set_config(id, arg))),
    rgblightSaveConfig: (id: string) =>
        wrap(ensureClient().then((c) => c.rgblight_save_config(id))),
    rgbmatrixCapabilities: (id: string) =>
        wrap(ensureClient().then((c) => c.rgbmatrix_capabilities(id))),
    rgbmatrixGetEnabledEffects: (id: string) =>
        wrap(ensureClient().then((c) => c.rgbmatrix_get_enabled_effects(id))),
    rgbmatrixGetConfig: (id: string) =>
        wrap(ensureClient().then((c) => c.rgbmatrix_get_config(id))),
    rgbmatrixSetConfig: (id: string, arg: unknown) =>
        wrap(ensureClient().then((c) => c.rgbmatrix_set_config(id, arg))),
    rgbmatrixSaveConfig: (id: string) =>
        wrap(ensureClient().then((c) => c.rgbmatrix_save_config(id))),
    audioCapabilities: (id: string) => wrap(ensureClient().then((c) => c.audio_capabilities(id))),
    audioGetConfig: (id: string) => wrap(ensureClient().then((c) => c.audio_get_config(id))),
    audioSetConfig: (id: string, arg: unknown) =>
        wrap(ensureClient().then((c) => c.audio_set_config(id, arg))),
    audioSaveConfig: (id: string) => wrap(ensureClient().then((c) => c.audio_save_config(id))),
})
