//! Split the tauri-specta generated `xap.ts` into a pure-types module and a
//! Tauri-wrappers module at generation time. See `split_generated`.

const GEN_COMMENT: &str = "// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.";

const TYPES_MARKER: &str = "/** user-defined types **/";
const GLOBALS_MARKER: &str = "/** tauri-specta globals **/";

fn strip_leading_comment(head: &str) -> &str {
    match head.split_once('\n') {
        Some((first, rest)) if first.trim_start().starts_with("// This file was generated") => rest,
        _ => head,
    }
}

/// Remove `//` line comments and `/* */` block comments. Good enough for the
/// generated head, which contains no strings holding comment-like sequences.
fn strip_comments(src: &str) -> String {
    let bytes = src.as_bytes();
    let mut out = String::with_capacity(src.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'/' && i + 1 < bytes.len() && bytes[i + 1] == b'/' {
            while i < bytes.len() && bytes[i] != b'\n' {
                i += 1;
            }
        } else if bytes[i] == b'/' && i + 1 < bytes.len() && bytes[i + 1] == b'*' {
            i += 2;
            while i + 1 < bytes.len() && !(bytes[i] == b'*' && bytes[i + 1] == b'/') {
                i += 1;
            }
            i += 2;
        } else {
            out.push(bytes[i] as char);
            i += 1;
        }
    }
    out
}

fn is_ident_char(c: char) -> bool {
    c.is_alphanumeric() || c == '_' || c == '$'
}

/// Whether `name` appears in `haystack` as a whole identifier (not as a
/// substring of a longer identifier).
fn references_ident(haystack: &str, name: &str) -> bool {
    let bytes = haystack.as_bytes();
    let mut start = 0;
    while let Some(pos) = haystack[start..].find(name) {
        let idx = start + pos;
        let before_ok = idx == 0
            || !haystack[..idx]
                .chars()
                .next_back()
                .map(is_ident_char)
                .unwrap_or(false);
        let after = idx + name.len();
        let after_ok = after >= bytes.len()
            || !haystack[after..]
                .chars()
                .next()
                .map(is_ident_char)
                .unwrap_or(false);
        if before_ok && after_ok {
            return true;
        }
        start = idx + name.len();
    }
    false
}

/// Split the generated TypeScript into `(xap_types, xap_tauri)`.
///
/// `xap_types` contains only the user-defined types plus the `Result` alias and
/// has no `@tauri-apps/api` dependency. `xap_tauri` contains the commands/events
/// and tauri-specta globals, importing the types from `./xap-types`.
pub fn split_generated(src: &str) -> (String, String) {
    let (head, rest) = src
        .split_once(TYPES_MARKER)
        .expect("missing `/** user-defined types **/` marker in generated xap.ts");
    let (types_block, globals) = rest
        .split_once(GLOBALS_MARKER)
        .expect("missing `/** tauri-specta globals **/` marker in generated xap.ts");

    let result_line = globals
        .lines()
        .find(|line| line.trim_start().starts_with("export type Result<T, E>"))
        .expect("missing `export type Result<T, E>` line in generated xap.ts")
        .trim()
        .to_string();

    let globals_without_result = globals
        .lines()
        .filter(|line| line.trim() != result_line)
        .collect::<Vec<_>>()
        .join("\n");

    let mut declared: Vec<String> = Vec::new();
    for line in types_block.lines() {
        let trimmed = line.trim_start();
        for prefix in ["export type ", "export interface "] {
            if let Some(rest) = trimmed.strip_prefix(prefix) {
                let name: String = rest
                    .chars()
                    .take_while(|c| c.is_alphanumeric() || *c == '_')
                    .collect();
                if !name.is_empty() {
                    declared.push(name);
                }
            }
        }
    }
    declared.push("Result".to_string());

    // Only import names actually referenced in the head (Region A); importing
    // unused names would trip TypeScript's `noUnusedLocals`. Check against a
    // comment-stripped copy so identifiers mentioned only in JSDoc prose
    // (e.g. `KeymapInfo.layer_count`) don't count as references.
    let head_body = strip_leading_comment(head).trim();
    let head_code = strip_comments(head_body);
    let names: Vec<String> = declared
        .into_iter()
        .filter(|name| references_ident(&head_code, name))
        .collect();

    let xap_types = format!("{GEN_COMMENT}\n\n{}\n\n{}\n", types_block.trim(), result_line);
    let xap_tauri = format!(
        "{GEN_COMMENT}\nimport type {{ {} }} from './xap-types'\n\n{}\n\n{}\n",
        names.join(", "),
        head_body,
        globals_without_result.trim(),
    );

    (xap_types, xap_tauri)
}

#[cfg(test)]
mod tests {
    use super::*;

    const SRC: &str = include_str!("../../src/generated/xap.ts");

    #[test]
    fn types_has_no_tauri_import() {
        let (types, _) = split_generated(SRC);
        assert!(!types.contains("@tauri-apps/api"));
    }

    #[test]
    fn types_has_result_and_user_type() {
        let (types, _) = split_generated(SRC);
        assert!(types.contains("export type Result<T, E>"));
        assert!(types.contains("export type XapVersionResponse"));
    }

    #[test]
    fn tauri_header_and_import() {
        let (_, tauri) = split_generated(SRC);
        assert!(tauri.starts_with(GEN_COMMENT));
        assert!(tauri.contains("import type {"));
        assert!(tauri.contains("} from './xap-types'"));
    }

    #[test]
    fn tauri_has_commands_and_globals() {
        let (_, tauri) = split_generated(SRC);
        assert!(tauri.contains("export const commands"));
        assert!(tauri.contains("function __makeEvents__"));
        assert!(tauri.contains("import { invoke as TAURI_INVOKE } from '@tauri-apps/api/core'"));
    }

    #[test]
    fn tauri_does_not_redefine_result() {
        let (_, tauri) = split_generated(SRC);
        assert!(!tauri.contains("export type Result<T, E> ="));
    }

    #[test]
    fn import_list_includes_expected_names() {
        let (_, tauri) = split_generated(SRC);
        let import_line = tauri
            .lines()
            .find(|line| line.starts_with("import type {"))
            .unwrap();
        assert!(import_line.contains("XapVersionResponse"));
        assert!(import_line.contains("Result"));
    }
}
